// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'main.dart';

List<RouteEntity> get routes => [
  RouteEntity(
    key: 'pages/core/home',
    uri: Uri.parse('pages/core/home'),
    routeBuilder: b0Builder,
  ),
  // RouteEntity(
  //   key: 'pages/core/management/income',
  //   uri: Uri.parse('pages/core/management/income'),
  //   routeBuilder: b1Builder,
  // ),
  RouteEntity(
    key: 'pages/login/forget_password',
    uri: Uri.parse('pages/login/forget_password'),
    routeBuilder: b2Builder,
  ),
  RouteEntity(
    key: 'pages/login/signin',
    uri: Uri.parse('pages/login/signin'),
    routeBuilder: b3Builder,
  ),
  RouteEntity(
    key: 'pages/login/signup',
    uri: Uri.parse('pages/login/signup'),
    routeBuilder: b4Builder,
  ),
  RouteEntity(
    key: 'pages/login/welcome',
    uri: Uri.parse('pages/login/welcome'),
    routeBuilder: b5Builder,
  ),
];

const routePaths = (
  path: '/',
  pages: (
    path: '/pages',
    core: (
      path: '/pages/core',
      home: '/pages/core/home',
      management: (
        path: '/pages/core/management',
        income: '/pages/core/management/income',
      ),
    ),
    login: (
      path: '/pages/login',
      forgetPassword: '/pages/login/forget_password',
      signin: '/pages/login/signin',
      signup: '/pages/login/signup',
      welcome: '/pages/login/welcome',
    ),
  ),
);
