// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:flutter/widgets.dart';
import 'package:routefly/routefly.dart';

import 'app/pages/core/home/home_page.dart' as a0;
import 'app/pages/core/management/income/income_page.dart' as a1;
import 'app/pages/login/forget_password_page.dart' as a2;
import 'app/pages/login/signin_page.dart' as a3;
import 'app/pages/login/signup_page.dart' as a4;
import 'app/pages/login/welcome_page.dart' as a5;

Route b0Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a0.HomePage());
Route b1Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a1.IncomePage());
Route b2Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a2.ForgetPasswordPage());
Route b3Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a3.SigninPage());
Route b4Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a4.SignupPage());
Route b5Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a5.WelcomePage());
